<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\BillRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity from profile
 * @profile data/data/2023/20_normalize/obj.profile.json
 */
#[Entity(repositoryClass: BillRepository::class)]
#[MeiliIndex(
	primaryKey: 'id',
	filterable: self::FILTERABLE_FIELDS,
	sortable: self::SORTABLE_FIELDS,
	searchable: self::SEARCHABLE_FIELDS,
)]
final class Bill
{
	public const FILTERABLE_FIELDS = [
		'chamber',
		'status',
		'dateIntroduced',
		'outcome',
		'copatronCount',
		'patronDistrict',
		'year',
		'patronParty',
		'patronChamber',
		'patronStarted',
		'patronAddress',
		'committee',
		'committeeShortname',
		'committeeChamber',
		'statusDetail',
		'statusDetailDate',
		'patronPrefix',
		'type',
	];

	public const SORTABLE_FIELDS = ['id', 'chiefPatronId', 'copatronCount', 'patronDistrict', 'patronStarted', 'wordCount'];
	public const SEARCHABLE_FIELDS = ['catchLine', 'summary', 'fullText', 'patronNameFormatted'];

	/**
	 * Profile field "id"
	 * @types int (storageHint=int)
	 * @stats total=3029, nulls=0, distinct=3029
	 */
	#[Column(type: Types::INTEGER, nullable: false)]
	#[Id]
	public ?int $id = null;

	/**
	 * Profile field "number"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=3029
	 */
	#[Column(length: 6, nullable: true)]
	public ?string $number = null;

	/**
	 * Profile field "session_id"
	 * @types int (storageHint=int)
	 * @stats total=3029, nulls=0, distinct=1
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $sessionId = null;

	/**
	 * Profile field "chamber"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=2
	 */
	#[Column(length: 6, nullable: true)]
	public ?string $chamber = null;

	/**
	 * Profile field "catch_line"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=2526
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $catchLine = null;

	/**
	 * Profile field "chief_patron_id"
	 * @types int (storageHint=int)
	 * @stats total=3029, nulls=0, distinct=143
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $chiefPatronId = null;

	/**
	 * Profile field "summary"
	 * @types string (storageHint=string)
	 * @stats total=3028, nulls=0, distinct=2862
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $summary = null;

	/**
	 * Profile field "summary_hash"
	 * @types string (storageHint=string)
	 * @stats total=3028, nulls=0, distinct=2798
	 */
	#[Column(length: 32, nullable: true)]
	public ?string $summaryHash = null;

	/**
	 * Profile field "full_text"
	 * @types string (storageHint=string)
	 * @stats total=3013, nulls=0, distinct=3013
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $fullText = null;

	/**
	 * Profile field "status"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=15
	 */
	#[Column(length: 18, nullable: true)]
	public ?string $status = null;

	/**
	 * Profile field "date_introduced"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=62
	 */
	#[Column(length: 10, nullable: true)]
	public ?string $dateIntroduced = null;

	/**
	 * Profile field "outcome"
	 * @types string (storageHint=string)
	 * @stats total=2099, nulls=0, distinct=2
	 */
	#[Column(length: 6, nullable: true)]
	public ?string $outcome = null;

	/**
	 * Profile field "copatron_count"
	 * @types int (storageHint=int)
	 * @stats total=3029, nulls=0, distinct=52
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $copatronCount = null;

	/**
	 * Profile field "patron"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=143
	 */
	#[Column(length: 25, nullable: true)]
	public ?string $patron = null;

	/**
	 * Profile field "patron_district"
	 * @types int (storageHint=int)
	 * @stats total=3029, nulls=0, distinct=78
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $patronDistrict = null;

	/**
	 * Profile field "year"
	 * @types int (storageHint=int)
	 * @stats total=3029, nulls=0, distinct=1
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $year = null;

	/**
	 * Profile field "session_lis_id"
	 * @types int (storageHint=int)
	 * @stats total=3029, nulls=0, distinct=1
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $sessionLisId = null;

	/**
	 * Profile field "patron_party"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=2
	 */
	#[Column(length: 1, nullable: true)]
	public ?string $patronParty = null;

	/**
	 * Profile field "patron_chamber"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=2
	 */
	#[Column(length: 6, nullable: true)]
	public ?string $patronChamber = null;

	/**
	 * Profile field "patron_shortname"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=143
	 */
	#[Column(length: 16, nullable: true)]
	public ?string $patronShortname = null;

	/**
	 * Profile field "patron_place"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=85
	 */
	#[Column(length: 16, nullable: true)]
	public ?string $patronPlace = null;

	/**
	 * Profile field "patron_started"
	 * @types int (storageHint=int)
	 * @stats total=3029, nulls=0, distinct=27
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $patronStarted = null;

	/**
	 * Profile field "patron_name_formatted"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=143
	 * @naturalLanguageLike true
	 * @localeGuess es
	 */
	#[Column(length: 44, nullable: true)]
	public ?string $patronNameFormatted = null;

	/**
	 * Profile field "patron_address"
	 * @types array (storageHint=json)
	 * @stats total=2896, nulls=0, distinct=137
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $patronAddress = null;

	/**
	 * Profile field "committee"
	 * @types string (storageHint=string)
	 * @stats total=1950, nulls=0, distinct=18
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[Column(length: 47, nullable: true)]
	public ?string $committee = null;

	/**
	 * Profile field "committee_shortname"
	 * @types string (storageHint=string)
	 * @stats total=1950, nulls=0, distinct=14
	 */
	#[Column(length: 15, nullable: true)]
	public ?string $committeeShortname = null;

	/**
	 * Profile field "committee_chamber"
	 * @types string (storageHint=string)
	 * @stats total=1950, nulls=0, distinct=2
	 */
	#[Column(length: 6, nullable: true)]
	public ?string $committeeChamber = null;

	/**
	 * Profile field "status_detail"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=15
	 */
	#[Column(length: 18, nullable: true)]
	public ?string $statusDetail = null;

	/**
	 * Profile field "status_detail_date"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=52
	 */
	#[Column(length: 10, nullable: true)]
	public ?string $statusDetailDate = null;

	/**
	 * Profile field "version"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=3029
	 */
	#[Column(length: 9, nullable: true)]
	public ?string $version = null;

	/**
	 * Profile field "word_count"
	 * @types int (storageHint=int)
	 * @stats total=3029, nulls=0, distinct=1579
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $wordCount = null;

	/**
	 * Profile field "patron_suffix"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=91
	 */
	#[Column(length: 20, nullable: true)]
	public ?string $patronSuffix = null;

	/**
	 * Profile field "patron_prefix"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=2
	 */
	#[Column(length: 4, nullable: true)]
	public ?string $patronPrefix = null;

	/**
	 * Profile field "url"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=3029
	 * @urlLike true
	 */
	#[Column(length: 50, nullable: true)]
	public ?string $url = null;

	/**
	 * Profile field "type"
	 * @types string (storageHint=string)
	 * @stats total=3029, nulls=0, distinct=2
	 */
	#[Column(length: 10, nullable: true)]
	public ?string $type = null;

	/**
	 * Profile field "tags"
	 * @types array (storageHint=json)
	 * @stats total=3028, nulls=0, distinct=3028
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $tags = null;

	/**
	 * Profile field "status_history"
	 * @types array (storageHint=json)
	 * @stats total=3029, nulls=0, distinct=3029
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $statusHistory = null;

	/**
	 * Profile field "text"
	 * @types array (storageHint=json)
	 * @stats total=3029, nulls=0, distinct=3029
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $text = null;

	/**
	 * Profile field "related"
	 * @types array (storageHint=json)
	 * @stats total=3005, nulls=0, distinct=2891
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $related = null;

	/**
	 * Profile field "changes"
	 * @types array (storageHint=json)
	 * @stats total=826, nulls=0, distinct=790
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $changes = null;

	/**
	 * Profile field "video"
	 * @types bool (storageHint=bool)
	 * @stats total=3029, nulls=0, distinct=1
	 * @booleanLike true
	 */
	#[Column(type: Types::BOOLEAN, nullable: true)]
	public ?bool $video = null;

	/**
	 * Profile field "duplicates"
	 * @types array (storageHint=json)
	 * @stats total=691, nulls=0, distinct=691
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $duplicates = null;

	/**
	 * Profile field "copatron"
	 * @types array (storageHint=json)
	 * @stats total=1538, nulls=0, distinct=770
	 */
	#[Column(type: Types::JSON, nullable: true)]
	public ?array $copatron = null;
}
