<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\BillRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity from profile
 * @profile data/bills.profile.json
 */
#[Entity(repositoryClass: BillRepository::class)]
#[MeiliIndex(
	primaryKey: 'id',
	filterable: self::FILTERABLE_FIELDS,
	sortable: self::SORTABLE_FIELDS,
	searchable: self::SEARCHABLE_FIELDS,
)]
final class Bill
{
	public const FILTERABLE_FIELDS = ['year', 'chamber', 'status', 'outcome'];
	public const SORTABLE_FIELDS = ['year'];
	public const SEARCHABLE_FIELDS = ['catchLine', 'summary'];

	/**
	 * Profile field "year"
	 * @original Year
	 * @types int (storageHint=int)
	 * @stats total=65840, nulls=0, distinct=21
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $year = null;

	/**
	 * Profile field "chamber"
	 * @original Chamber
	 * @types string (storageHint=string)
	 * @stats total=65840, nulls=0, distinct=2
	 */
	#[Column(length: 6, nullable: true)]
	public ?string $chamber = null;

	/**
	 * Profile field "bill"
	 * @original Bill #
	 * @types string (storageHint=string)
	 * @stats total=65840, nulls=0, distinct=8832
	 */
	#[Column(length: 7, nullable: true)]
	public ?string $bill = null;

	/**
	 * Profile field "catchLine"
	 * @original Catch Line
	 * @types string (storageHint=string)
	 * @stats total=65840, nulls=0, distinct=50097
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[Column(length: 235, nullable: true)]
	public ?string $catchLine = null;

	/**
	 * Profile field "patron"
	 * @original Patron
	 * @types string (storageHint=string)
	 * @stats total=65761, nulls=0, distinct=366
	 */
	#[Column(length: 28, nullable: true)]
	public ?string $patron = null;

	/**
	 * Profile field "summary"
	 * @original Summary
	 * @types string (storageHint=string)
	 * @stats total=64904, nulls=0, distinct=56438
	 * @naturalLanguageLike true
	 * @localeGuess en
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $summary = null;

	/**
	 * Profile field "status"
	 * @original Status
	 * @types string (storageHint=string)
	 * @stats total=65827, nulls=0, distinct=21
	 */
	#[Column(length: 19, nullable: true)]
	public ?string $status = null;

	/**
	 * Profile field "dateIntroduced"
	 * @original Date Introduced
	 * @types string (storageHint=string)
	 * @stats total=65809, nulls=0, distinct=1853
	 */
	#[Column(length: 10, nullable: true)]
	public ?string $dateIntroduced = null;

	/**
	 * Profile field "id"
	 * @types string (storageHint=string)
	 * @stats total=65840, nulls=0, distinct=65840
	 */
	#[Column(length: 12, nullable: false)]
	#[Id]
	public ?string $id = null;

	/**
	 * Profile field "outcome"
	 * @original Outcome
	 * @types string (storageHint=string)
	 * @stats total=38436, nulls=0, distinct=2
	 */
	#[Column(length: 6, nullable: true)]
	public ?string $outcome = null;
}
