<?php

namespace App\Controller\Admin;

use App\Entity\Bill;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use Survos\EzBundle\Controller\AbstractEzCrudController;
use Survos\EzBundle\Field\LinkedTextField;

/**
 * Generated by code:meili:admin
 */
final class BillCrudController extends AbstractEzCrudController
{
    /** TODO: adjust SHOW_ROUTE to your app show route */
    public const SHOW_ROUTE = 'admin_app_bill_show';

    public static function getEntityFqcn(): string
    {
        return \App\Entity\Bill::class;
    }

    protected function preferredFields(string $pageName): iterable
    {
        if ($pageName !== Crud::PAGE_INDEX) {
            return [];
        }
        return [];

//        yield LinkedTextField::new('id', 'Id')
//            ->setRoute(self::SHOW_ROUTE, 'id', 'id');
    }
}
