<?php

namespace App\Controller\Admin;

use EasyCorp\Bundle\EasyAdminBundle\Attribute\AdminDashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\Assets;
use EasyCorp\Bundle\EasyAdminBundle\Config\Dashboard;
use EasyCorp\Bundle\EasyAdminBundle\Config\MenuItem;
use Survos\MeiliBundle\Controller\AbstractMeiliController;

/**
 * Generated by code:meili:admin
 */
#[AdminDashboard('/ez', self::MEILI_ROUTE)]
final class MeiliDashboardController extends AbstractMeiliController
{
    public const MEILI_ROUTE = 'meili_admin';

    public function configureDashboard(): Dashboard
    {
        return parent::configureDashboard()
            ->setTitle('Richmond Sunshine');
    }

    public function configureMenuItems(): iterable
    {
        yield from parent::configureMenuItems();

        yield MenuItem::linkToRoute('Bill UX Search', 'tabler:search', 'survos_entity_ux_search', [
            'code' => 'bill',
        ]);
    }
}
