<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260503155532 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bill (id INT NOT NULL, number VARCHAR(6) DEFAULT NULL, session_id INT DEFAULT NULL, chamber VARCHAR(6) DEFAULT NULL, catch_line TEXT DEFAULT NULL, chief_patron_id INT DEFAULT NULL, summary TEXT DEFAULT NULL, summary_hash VARCHAR(32) DEFAULT NULL, full_text TEXT DEFAULT NULL, status VARCHAR(18) DEFAULT NULL, date_introduced VARCHAR(10) DEFAULT NULL, outcome VARCHAR(6) DEFAULT NULL, copatron_count INT DEFAULT NULL, patron VARCHAR(25) DEFAULT NULL, patron_district INT DEFAULT NULL, year INT DEFAULT NULL, session_lis_id INT DEFAULT NULL, patron_party VARCHAR(1) DEFAULT NULL, patron_chamber VARCHAR(6) DEFAULT NULL, patron_shortname VARCHAR(16) DEFAULT NULL, patron_place VARCHAR(16) DEFAULT NULL, patron_started INT DEFAULT NULL, patron_name_formatted VARCHAR(44) DEFAULT NULL, patron_address JSON DEFAULT NULL, committee VARCHAR(47) DEFAULT NULL, committee_shortname VARCHAR(15) DEFAULT NULL, committee_chamber VARCHAR(6) DEFAULT NULL, status_detail VARCHAR(18) DEFAULT NULL, status_detail_date VARCHAR(10) DEFAULT NULL, version VARCHAR(9) DEFAULT NULL, word_count INT DEFAULT NULL, patron_suffix VARCHAR(20) DEFAULT NULL, patron_prefix VARCHAR(4) DEFAULT NULL, url VARCHAR(50) DEFAULT NULL, type VARCHAR(10) DEFAULT NULL, tags JSON DEFAULT NULL, status_history JSON DEFAULT NULL, text JSON DEFAULT NULL, related JSON DEFAULT NULL, changes JSON DEFAULT NULL, video BOOLEAN DEFAULT NULL, duplicates JSON DEFAULT NULL, copatron JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE candidate (candidate_key VARCHAR(160) NOT NULL, provider_code VARCHAR(32) NOT NULL, source_id VARCHAR(160) DEFAULT NULL, kind VARCHAR(32) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, source_url VARCHAR(500) DEFAULT NULL, locale VARCHAR(16) DEFAULT NULL, country VARCHAR(8) DEFAULT NULL, dataset_key VARCHAR(160) DEFAULT NULL, status VARCHAR(32) NOT NULL, meta JSONB NOT NULL, discovered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, hydrated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, promoted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, provider_entity_code VARCHAR(32) DEFAULT NULL, PRIMARY KEY (candidate_key))');
        $this->addSql('CREATE INDEX IDX_C8B28E44FA460441 ON candidate (provider_entity_code)');
        $this->addSql('CREATE INDEX IDX_C8B28E44929D53E4 ON candidate (provider_code)');
        $this->addSql('CREATE INDEX IDX_C8B28E447B00651C ON candidate (status)');
        $this->addSql('CREATE TABLE dataset_info (dataset_key VARCHAR(128) NOT NULL, label VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, aggregator VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, contact_url VARCHAR(255) DEFAULT NULL, rights_uri VARCHAR(255) DEFAULT NULL, obj_count INT NOT NULL, meta_path VARCHAR(255) DEFAULT NULL, raw_path VARCHAR(255) DEFAULT NULL, normalized_path VARCHAR(255) DEFAULT NULL, profile_path VARCHAR(255) DEFAULT NULL, pixie_db_path VARCHAR(255) DEFAULT NULL, status VARCHAR(32) NOT NULL, normalized_count INT DEFAULT NULL, pixie_row_count INT DEFAULT NULL, meili_doc_count INT DEFAULT NULL, last_scanned TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_normalized TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_indexed TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, cores JSON NOT NULL, fields JSONB NOT NULL, profile_summary JSONB DEFAULT NULL, meili_settings JSONB NOT NULL, meta JSONB NOT NULL, provider_code VARCHAR(32) DEFAULT NULL, PRIMARY KEY (dataset_key))');
        $this->addSql('CREATE INDEX IDX_4E0D6452929D53E4 ON dataset_info (provider_code)');
        $this->addSql('CREATE INDEX IDX_4E0D6452BB5381D3 ON dataset_info (aggregator)');
        $this->addSql('CREATE INDEX IDX_4E0D64524180C698 ON dataset_info (locale)');
        $this->addSql('CREATE INDEX IDX_4E0D64527B00651C ON dataset_info (status)');
        $this->addSql('CREATE TABLE fetch_page (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_code VARCHAR(32) NOT NULL, dataset_key VARCHAR(190) NOT NULL, kind VARCHAR(32) NOT NULL, page_number INT NOT NULL, url VARCHAR(2048) NOT NULL, status VARCHAR(32) NOT NULL, content_type VARCHAR(255) DEFAULT NULL, accept VARCHAR(255) DEFAULT NULL, archive_path VARCHAR(2048) DEFAULT NULL, record_count INT DEFAULT NULL, error VARCHAR(1024) DEFAULT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSON DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_fetch_page ON fetch_page (provider_code, dataset_key, kind, page_number)');
        $this->addSql('CREATE TABLE fetch_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider_code VARCHAR(32) NOT NULL, dataset_key VARCHAR(190) NOT NULL, kind VARCHAR(32) NOT NULL, row_number INT NOT NULL, source_id VARCHAR(255) DEFAULT NULL, record_type VARCHAR(32) DEFAULT NULL, payload TEXT NOT NULL, payload_bytes INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fetch_page_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FB10B11C9F2FB857 ON fetch_record (fetch_page_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_fetch_record_page_row ON fetch_record (fetch_page_id, row_number)');
        $this->addSql('CREATE TABLE index_info (index_name VARCHAR(255) NOT NULL, last_indexed TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, document_count INT NOT NULL, settings JSONB NOT NULL, task_id VARCHAR(255) DEFAULT NULL, primary_key VARCHAR(255) NOT NULL, batch_id VARCHAR(255) DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, label VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, aggregator VARCHAR(255) DEFAULT NULL, institution VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, locale VARCHAR(255) DEFAULT NULL, PRIMARY KEY (index_name))');
        $this->addSql('CREATE TABLE provider (code VARCHAR(32) NOT NULL, label VARCHAR(255) DEFAULT NULL, description TEXT DEFAULT NULL, homepage VARCHAR(500) DEFAULT NULL, logo VARCHAR(500) DEFAULT NULL, approx_inst_count INT DEFAULT NULL, approx_obj_count INT DEFAULT NULL, default_locale VARCHAR(10) DEFAULT NULL, data_reuse VARCHAR(255) DEFAULT NULL, terms_url VARCHAR(255) DEFAULT NULL, dataset_count INT DEFAULT NULL, synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (code))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE candidate ADD CONSTRAINT FK_C8B28E44FA460441 FOREIGN KEY (provider_entity_code) REFERENCES provider (code) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dataset_info ADD CONSTRAINT FK_4E0D6452929D53E4 FOREIGN KEY (provider_code) REFERENCES provider (code) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fetch_record ADD CONSTRAINT FK_FB10B11C9F2FB857 FOREIGN KEY (fetch_page_id) REFERENCES fetch_page (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE candidate DROP CONSTRAINT FK_C8B28E44FA460441');
        $this->addSql('ALTER TABLE dataset_info DROP CONSTRAINT FK_4E0D6452929D53E4');
        $this->addSql('ALTER TABLE fetch_record DROP CONSTRAINT FK_FB10B11C9F2FB857');
        $this->addSql('DROP TABLE bill');
        $this->addSql('DROP TABLE candidate');
        $this->addSql('DROP TABLE dataset_info');
        $this->addSql('DROP TABLE fetch_page');
        $this->addSql('DROP TABLE fetch_record');
        $this->addSql('DROP TABLE index_info');
        $this->addSql('DROP TABLE provider');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
