<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\UX\StimulusBundle\StimulusBundle::class => ['all' => true],
    Symfony\UX\Turbo\TurboBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Survos\JsonlBundle\SurvosJsonlBundle::class => ['all' => true],
    Survos\JsTwigBundle\SurvosJsTwigBundle::class => ['all' => true],
    Survos\MeiliBundle\SurvosMeiliBundle::class => ['all' => true],
    Survos\StateBundle\SurvosStateBundle::class => ['all' => true],
    Survos\ImportBundle\SurvosImportBundle::class => ['all' => true],
    Survos\CodeBundle\SurvosCodeBundle::class => ['dev' => true, 'test' => true],
    Symfony\UX\TwigComponent\TwigComponentBundle::class => ['all' => true],
    EasyCorp\Bundle\EasyAdminBundle\EasyAdminBundle::class => ['all' => true],
    Survos\EzBundle\SurvosEzBundle::class => ['all' => true],
    Survos\TablerBundle\SurvosTablerBundle::class => ['all' => true],
    Survos\AdminBundle\SurvosAdminBundle::class => ['all' => true],
    Symfony\UX\Icons\UXIconsBundle::class => ['all' => true],
    Survos\DeploymentBundle\SurvosDeploymentBundle::class => ['dev' => true, 'test' => true],
    Inspector\Symfony\Bundle\InspectorBundle::class => ['all' => true],
    Symfony\UX\Chartjs\ChartjsBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Survos\AtlasBundle\SurvosAtlasBundle::class => ['all' => true],
    Survos\Kit\SurvosKitBundle::class => ['all' => true],
    Survos\FieldBundle\SurvosFieldBundle::class => ['all' => true],
    Symfony\UX\LiveComponent\LiveComponentBundle::class => ['all' => true],
    Mezcalito\UxSearchBundle\MezcalitoUxSearchBundle::class => ['all' => true],
    Survos\SearchBundle\SurvosSearchBundle::class => ['all' => true],
];
